import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaNeonHttp } from "@prisma/adapter-neon";

const connectionString = process.env.DATABASE_URL!;
const adapter = new PrismaNeonHttp(connectionString, {} as any);
const prisma = new PrismaClient({ adapter: adapter as any });

interface TopicData {
  slug: string;
  title: string;
  description: string;
  difficulty: "EASY" | "MEDIUM" | "HARD";
  rubricAtoms: string[];
}

interface DomainData {
  slug: string;
  name: string;
  description: string;
  categories: {
    slug: string;
    name: string;
    description: string;
    topics: TopicData[];
  }[];
}

const DOMAINS_DATA: DomainData[] = [
  {
    slug: "system-design",
    name: "System Design",
    description: "Architecture, scalability, distributed systems, and real-world trade-offs.",
    categories: [
      {
        slug: "distributed-architecture",
        name: "Distributed Architecture & Scale",
        description: "Core architectural foundations for high-scale distributed systems.",
        topics: [
          {
            slug: "consistent-hashing",
            title: "Consistent Hashing & DHT",
            description: "Partitioning data and virtual nodes on hash rings.",
            difficulty: "MEDIUM",
            rubricAtoms: ["virtual nodes", "hash ring", "rebalancing"],
          },
          {
            slug: "rate-limiter",
            title: "Rate Limiting & Throttling",
            description: "Token bucket, leaky bucket, sliding window rate limiters.",
            difficulty: "MEDIUM",
            rubricAtoms: ["token bucket", "sliding window", "redis atomic"],
          },
          {
            slug: "distributed-cache",
            title: "Distributed Cache Architecture",
            description: "Memcached vs Redis, cache eviction, cache stampede prevention.",
            difficulty: "HARD",
            rubricAtoms: ["cache-aside", "write-through", "lru eviction"],
          },
          {
            slug: "url-shortener",
            title: "URL Shortener at Scale (TinyURL)",
            description: "Base62 encoding, distributed ID generation, high read throughput.",
            difficulty: "EASY",
            rubricAtoms: ["base62", "kgs", "bloom filter"],
          },
          {
            slug: "load-balancing",
            title: "Load Balancing & Traffic Routing",
            description: "L4 vs L7 load balancing, consistent hash routing, health checks.",
            difficulty: "MEDIUM",
            rubricAtoms: ["round-robin", "least connections", "l7 ingress"],
          },
          {
            slug: "database-sharding",
            title: "Database Sharding & Partitioning",
            description: "Horizontal vs vertical partitioning, cross-shard queries, re-sharding.",
            difficulty: "HARD",
            rubricAtoms: ["shard key", "consistent hash", "distributed join"],
          },
          {
            slug: "cap-theorem",
            title: "CAP & PACELC Theorems in Practice",
            description: "Consistency vs availability trade-offs in distributed datastores.",
            difficulty: "EASY",
            rubricAtoms: ["linearizability", "eventual consistency", "partition tolerance"],
          },
          {
            slug: "microservices-architecture",
            title: "Microservices & Service Mesh",
            description: "Decomposition, inter-service communication, Envoy sidecar patterns.",
            difficulty: "MEDIUM",
            rubricAtoms: ["grpc", "service mesh", "circuit breaker"],
          },
          {
            slug: "api-design-patterns",
            title: "API Design & Versioning at Scale",
            description: "REST, GraphQL, gRPC trade-offs, pagination, idempotency keys.",
            difficulty: "EASY",
            rubricAtoms: ["cursor pagination", "idempotency", "protobuf"],
          },
          {
            slug: "message-queues",
            title: "Message Queues & Event Streaming",
            description: "Kafka vs RabbitMQ, log-based pub/sub, at-least-once delivery.",
            difficulty: "HARD",
            rubricAtoms: ["partitioning", "consumer groups", "backpressure"],
          },
          {
            slug: "distributed-consensus",
            title: "Distributed Consensus & Raft",
            description: "Leader election, log replication, safety guarantees under split-brain.",
            difficulty: "HARD",
            rubricAtoms: ["raft", "leader election", "quorum"],
          },
          {
            slug: "content-delivery-network",
            title: "CDN & Edge Caching Architecture",
            description: "Point-of-presence (PoP) routing, cache invalidation, edge compute.",
            difficulty: "MEDIUM",
            rubricAtoms: ["anycast", "edge caching", "origin shielding"],
          },
          {
            slug: "search-indexing",
            title: "Search Indexing & Elasticsearch",
            description: "Inverted index, distributed shard routing, TF-IDF / BM25 relevance.",
            difficulty: "HARD",
            rubricAtoms: ["inverted index", "segment merging", "document routing"],
          },
          {
            slug: "sql-vs-nosql",
            title: "SQL vs NoSQL Deep-Dive Trade-offs",
            description: "ACID transactions vs tunable consistency, document, key-value, column.",
            difficulty: "MEDIUM",
            rubricAtoms: ["acid", "base", "normalization"],
          },
          {
            slug: "circuit-breakers",
            title: "Resiliency, Retries & Circuit Breakers",
            description: "Preventing cascading failures via Hystrix / Resilience4j patterns.",
            difficulty: "MEDIUM",
            rubricAtoms: ["open state", "half-open", "exponential backoff"],
          },
          {
            slug: "distributed-transactions",
            title: "Distributed Transactions & Saga Pattern",
            description: "2PC vs Choreography vs Orchestration Sagas with compensating actions.",
            difficulty: "HARD",
            rubricAtoms: ["2pc", "orchestration saga", "compensating action"],
          },
          {
            slug: "websockets-realtime",
            title: "Real-Time WebSockets & SSE Architecture",
            description: "Scaling persistent connections, horizontal scaling with Redis Pub/Sub.",
            difficulty: "MEDIUM",
            rubricAtoms: ["heartbeats", "connection multiplexing", "pub-sub broker"],
          },
          {
            slug: "unique-id-generation",
            title: "Distributed Unique ID Generation (Snowflake)",
            description: "Twitter Snowflake, UUIDv7, auto-increment bottlenecks.",
            difficulty: "MEDIUM",
            rubricAtoms: ["64-bit id", "worker id", "clock skew"],
          },
          {
            slug: "data-lake-batch",
            title: "Data Lake & Batch Processing Architecture",
            description: "Lambda vs Kappa architectures, Parquet storage, Apache Spark/Flink.",
            difficulty: "HARD",
            rubricAtoms: ["lambda", "kappa", "columnar storage"],
          },
          {
            slug: "disaster-recovery",
            title: "Disaster Recovery & Multi-Region Replication",
            description: "RPO/RTO metrics, active-active vs active-passive failover.",
            difficulty: "HARD",
            rubricAtoms: ["rpo", "rto", "geo-dns failover"],
          },
          {
            slug: "whatsapp-chat",
            title: "WhatsApp / Messenger Real-Time Chat",
            description: "One-on-one and group messaging, delivery receipts, offline storage.",
            difficulty: "HARD",
            rubricAtoms: ["last-seen", "delivery receipts", "websocket session"],
          },
          {
            slug: "uber-geo-dispatch",
            title: "Uber / Ride-Sharing Geo-Dispatch",
            description: "Quadtree vs S2 vs H3 geospatial indexing, driver location tracking.",
            difficulty: "HARD",
            rubricAtoms: ["spatial index", "h3 hex", "eta matching"],
          },
          {
            slug: "youtube-video-platform",
            title: "YouTube / Netflix Video Streaming",
            description: "Video ingestion, adaptive bitrate chunking (HLS/DASH), CDN caching.",
            difficulty: "HARD",
            rubricAtoms: ["transcoding", "hls manifests", "chunked upload"],
          },
          {
            slug: "payment-gateway",
            title: "Payment Gateway & Double-Entry Ledger",
            description: "Strict idempotency keys, two-phase commits, immutable ledger entries.",
            difficulty: "HARD",
            rubricAtoms: ["double-entry", "idempotency key", "reconciliation"],
          },
          {
            slug: "crawler-search-engine",
            title: "Distributed Web Crawler Architecture",
            description: "Frontier queue management, robots.txt compliance, deduplication bloom.",
            difficulty: "HARD",
            rubricAtoms: ["url frontier", "politeness", "bloom filter"],
          },
          {
            slug: "distributed-file-system",
            title: "Distributed File System (GFS/HDFS)",
            description: "NameNode metadata, chunkservers, 3x replication, heartbeat checks.",
            difficulty: "HARD",
            rubricAtoms: ["chunkserver", "block replication", "lease renewal"],
          },
          {
            slug: "notification-system",
            title: "Multi-Channel Notification System",
            description: "Push, SMS, email fan-out, prioritization queues, rate limiting per user.",
            difficulty: "MEDIUM",
            rubricAtoms: ["fan-out queue", "provider fallback", "rate limit per user"],
          },
          {
            slug: "news-feed-system",
            title: "Twitter / Facebook News Feed Architecture",
            description: "Push vs pull model, timeline generation, celebrity hot-key handling.",
            difficulty: "HARD",
            rubricAtoms: ["fan-out-on-write", "fan-out-on-read", "redis timeline"],
          },
          {
            slug: "metrics-observability",
            title: "Time-Series Metrics & Telemetry (Prometheus)",
            description: "High-cardinality storage, downsampling, alert rule evaluation.",
            difficulty: "HARD",
            rubricAtoms: ["gorilla compression", "tsdb", "high cardinality"],
          },
          {
            slug: "distributed-lock",
            title: "Distributed Lock Manager (Redlock)",
            description: "Redis single-instance lock vs Redlock algorithm, lease expiration.",
            difficulty: "MEDIUM",
            rubricAtoms: ["fencing token", "lease time", "redlock"],
          },
          {
            slug: "leaderboard-gaming",
            title: "Real-Time Gaming Leaderboard",
            description: "Redis Sorted Sets (ZSET), skip lists, top-100 pagination under high QPS.",
            difficulty: "MEDIUM",
            rubricAtoms: ["zset", "skip list", "rank computation"],
          },
          {
            slug: "google-drive-sync",
            title: "Google Drive / Dropbox File Sync Engine",
            description: "Chunking, delta sync, conflict resolution, deduplication.",
            difficulty: "HARD",
            rubricAtoms: ["content-defined chunking", "delta sync", "sync conflict"],
          },
          {
            slug: "typeahead-autosuggest",
            title: "Typeahead Autosuggest & Search Suggestion",
            description: "Trie with prefix caching, frequency weighting, sampling pipelines.",
            difficulty: "MEDIUM",
            rubricAtoms: ["prefix trie", "top-k suggestions", "frequency cache"],
          },
          {
            slug: "event-sourcing-cqrs",
            title: "Event Sourcing & CQRS Pattern",
            description: "Append-only event stores, projection hydration, read/write segregation.",
            difficulty: "HARD",
            rubricAtoms: ["event stream", "read projection", "snapshotting"],
          },
          {
            slug: "distributed-tracing",
            title: "Distributed Tracing Architecture (OpenTelemetry)",
            description: "Trace ID propagation, span trees, head vs tail sampling.",
            difficulty: "HARD",
            rubricAtoms: ["w3c tracecontext", "tail-based sampling", "span context"],
          },
          {
            slug: "ad-click-aggregation",
            title: "Real-Time Ad Click Aggregator",
            description: "Stream processing, tumbling windows, deduplication, billing accuracy.",
            difficulty: "HARD",
            rubricAtoms: ["tumbling window", "sliding window", "exactly-once"],
          },
          {
            slug: "ticketmaster-booking",
            title: "Ticketmaster / High-Concurrency Booking",
            description: "Seat hold expiration, flash sale mitigation, distributed locks.",
            difficulty: "HARD",
            rubricAtoms: ["seat hold ttl", "virtual waiting room", "optimistic lock"],
          },
          {
            slug: "collaborative-editor",
            title: "Collaborative Real-Time Editor (Google Docs)",
            description: "Operational Transformation (OT) vs CRDTs, undo/redo stacks.",
            difficulty: "HARD",
            rubricAtoms: ["crdt", "operational transformation", "state vector"],
          },
          {
            slug: "api-gateway-mesh",
            title: "Enterprise API Gateway Architecture",
            description: "Auth verification, dynamic routing, circuit breaking, request logging.",
            difficulty: "MEDIUM",
            rubricAtoms: ["jwt verification", "dynamic upstream", "tls termination"],
          },
          {
            slug: "feature-flag-system",
            title: "High-Throughput Feature Flagging (LaunchDarkly)",
            description: "Rule evaluation engine, local cache hydration, percentage rollout.",
            difficulty: "MEDIUM",
            rubricAtoms: ["hash-based rollout", "client evaluation", "stream updates"],
          },
        ],
      },
    ],
  },
  {
    slug: "coding",
    name: "Coding & Algorithms",
    description: "Core algorithms, data structures, and optimal time-space trade-offs.",
    categories: [
      {
        slug: "data-structures-algorithms",
        name: "Data Structures & Core Patterns",
        description: "Essential algorithmic patterns tested in top engineering interviews.",
        topics: [
          {
            slug: "sliding-window",
            title: "Sliding Window Pattern",
            description: "Fixed and variable window sizes for optimal subarray solutions.",
            difficulty: "MEDIUM",
            rubricAtoms: ["left/right pointers", "window state", "o(n) time"],
          },
          {
            slug: "two-pointers",
            title: "Two Pointers Technique",
            description: "Converging pointers, sorted arrays, palindrome validation.",
            difficulty: "EASY",
            rubricAtoms: ["left/right bounds", "sorted input", "in-place swap"],
          },
          {
            slug: "fast-slow-pointers",
            title: "Fast & Slow Pointers (Floyd's Cycle)",
            description: "Cycle detection in linked lists and sequence loops.",
            difficulty: "EASY",
            rubricAtoms: ["cycle detection", "midpoint search", "constant space"],
          },
          {
            slug: "monotonic-stack",
            title: "Monotonic Stack Pattern",
            description: "Next greater element, histogram areas, daily temperatures.",
            difficulty: "MEDIUM",
            rubricAtoms: ["stack invariant", "next greater element", "o(n) scan"],
          },
          {
            slug: "top-k-elements",
            title: "Top K Frequent Elements (Heaps)",
            description: "Min-heap vs max-heap, streaming data selection, quickselect.",
            difficulty: "MEDIUM",
            rubricAtoms: ["min-heap", "frequency map", "o(n log k)"],
          },
          {
            slug: "k-way-merge",
            title: "K-Way Merge with Priority Queues",
            description: "Merging sorted linked lists, streams, and external sorting.",
            difficulty: "HARD",
            rubricAtoms: ["priority queue", "stream merge", "heap node"],
          },
          {
            slug: "binary-search-answers",
            title: "Binary Search on Answer Space",
            description: "Capacity ship packages, split array largest sum, monotonic predicates.",
            difficulty: "MEDIUM",
            rubricAtoms: ["predicate function", "search range", "o(log(max-min))"],
          },
          {
            slug: "trie-prefix-tree",
            title: "Trie (Prefix Tree) Implementation",
            description: "Word dictionary, autocomplete, wildcard search with backtracking.",
            difficulty: "MEDIUM",
            rubricAtoms: ["trie node", "prefix matching", "character array"],
          },
          {
            slug: "graph-bfs-dfs",
            title: "Graph Traversals (BFS & DFS)",
            description: "Connected components, cycle detection, clone graph.",
            difficulty: "MEDIUM",
            rubricAtoms: ["visited set", "recursion stack", "adjacency list"],
          },
          {
            slug: "topological-sort",
            title: "Topological Sort & Kahn's Algorithm",
            description: "Course schedule, build order dependencies, in-degree arrays.",
            difficulty: "MEDIUM",
            rubricAtoms: ["in-degree array", "queue processing", "dag cycle detection"],
          },
          {
            slug: "dijkstra-shortest-path",
            title: "Dijkstra's Shortest Path Algorithm",
            description: "Weighted graphs, priority queue distance relaxation.",
            difficulty: "HARD",
            rubricAtoms: ["min-heap distance", "visited relaxation", "non-negative weights"],
          },
          {
            slug: "union-find-dsu",
            title: "Disjoint Set Union (Union-Find)",
            description: "Connected components, redundancy detection, Kruskal's MST.",
            difficulty: "MEDIUM",
            rubricAtoms: ["path compression", "union by rank", "parent pointers"],
          },
          {
            slug: "dynamic-programming-1d",
            title: "1D Dynamic Programming: Fib & Climb",
            description: "House robber, coin change, decode ways, jump game.",
            difficulty: "MEDIUM",
            rubricAtoms: ["state transition", "memoization table", "space optimization"],
          },
          {
            slug: "dynamic-programming-grid",
            title: "2D Grid Dynamic Programming",
            description: "Unique paths, minimum path sum, maximal square in binary matrix.",
            difficulty: "MEDIUM",
            rubricAtoms: ["dp table", "boundary conditions", "rolling row"],
          },
          {
            slug: "dynamic-programming-knapsack",
            title: "0/1 Knapsack & Subset Sum",
            description: "Subset partition, target sum, bounded resource optimization.",
            difficulty: "HARD",
            rubricAtoms: ["capacity iteration", "included/excluded", "1d state reduction"],
          },
          {
            slug: "dynamic-programming-lcs",
            title: "Longest Common Subsequence & Edit Distance",
            description: "String alignment, diff algorithms, transformation cost.",
            difficulty: "HARD",
            rubricAtoms: ["2d matrix matching", "substitution cost", "memoized recur"],
          },
          {
            slug: "backtracking-permutations",
            title: "Backtracking: Permutations & Combinations",
            description: "Subsets, combination sum, permutation generation.",
            difficulty: "MEDIUM",
            rubricAtoms: ["decision tree", "pruning branch", "state restore"],
          },
          {
            slug: "backtracking-n-queens",
            title: "Backtracking: N-Queens & Sudoku Solver",
            description: "Constraint satisfaction, row/column/diagonal bitmask sets.",
            difficulty: "HARD",
            rubricAtoms: ["bitmask lookup", "safe placement", "early backtrack"],
          },
          {
            slug: "intervals-merge",
            title: "Intervals: Merge & Insert Intervals",
            description: "Sorting by start time, overlapping interval reduction.",
            difficulty: "MEDIUM",
            rubricAtoms: ["sort by start", "overlap condition", "max end time"],
          },
          {
            slug: "intervals-meeting-rooms",
            title: "Intervals: Meeting Rooms II (Min Conference Rooms)",
            description: "Sweep-line algorithm, chronological event sorting.",
            difficulty: "MEDIUM",
            rubricAtoms: ["chronological events", "sweep line", "room counter"],
          },
          {
            slug: "linked-list-reversal",
            title: "In-Place Reversal of Linked List",
            description: "Reverse between bounds, k-group reversal, pointer rearrangement.",
            difficulty: "MEDIUM",
            rubricAtoms: ["prev/curr/next pointers", "sublist reattachment", "dummy head"],
          },
          {
            slug: "binary-tree-inversion",
            title: "Binary Tree BFS & Level Order Traversal",
            description: "Zigzag traversal, vertical order, right-side view.",
            difficulty: "EASY",
            rubricAtoms: ["queue level size", "level array", "tree serialization"],
          },
          {
            slug: "binary-tree-lca",
            title: "Lowest Common Ancestor (BST & Binary Tree)",
            description: "Recursive search, parent tracking, ancestral divergence.",
            difficulty: "MEDIUM",
            rubricAtoms: ["recursive ancestor", "bst value property", "split point"],
          },
          {
            slug: "binary-tree-max-path",
            title: "Binary Tree Maximum Path Sum",
            description: "Subtree path returns, global max update across split nodes.",
            difficulty: "HARD",
            rubricAtoms: ["split path", "gain function", "postorder traversal"],
          },
          {
            slug: "word-break-problem",
            title: "Word Break I & II",
            description: "Dictionary lookup, DP memoization, trie-accelerated segmenting.",
            difficulty: "HARD",
            rubricAtoms: ["prefix substring", "boolean dp", "path reconstruction"],
          },
          {
            slug: "lru-cache-design",
            title: "LRU Cache (Doubly Linked List + Hash Map)",
            description: "O(1) get and put, head/tail dummy nodes, node extraction.",
            difficulty: "MEDIUM",
            rubricAtoms: ["doubly linked list", "hash map", "o(1) eviction"],
          },
          {
            slug: "lfu-cache-design",
            title: "LFU Cache (Least Frequently Used)",
            description: "Frequency buckets, min-frequency tracking, O(1) eviction.",
            difficulty: "HARD",
            rubricAtoms: ["frequency map", "doubly linked lists", "min-freq pointer"],
          },
          {
            slug: "median-data-stream",
            title: "Find Median from Data Stream",
            description: "Dual-heap balance (max-heap lower half, min-heap upper half).",
            difficulty: "HARD",
            rubricAtoms: ["two heaps", "rebalance invariant", "o(1) median"],
          },
          {
            slug: "trapping-rain-water",
            title: "Trapping Rain Water (Two Pointers & Stack)",
            description: "Left-max and right-max barriers, elevation area accumulation.",
            difficulty: "HARD",
            rubricAtoms: ["two pointers", "min boundary", "monotonic stack"],
          },
          {
            slug: "largest-rectangle-histogram",
            title: "Largest Rectangle in Histogram",
            description: "Monotonic increasing stack, boundary width expansion.",
            difficulty: "HARD",
            rubricAtoms: ["monotonic stack", "area calculate", "left/right bounds"],
          },
          {
            slug: "sliding-window-maximum",
            title: "Sliding Window Maximum (Monotonic Deque)",
            description: "Decreasing monotonic deque, expired index ejection.",
            difficulty: "HARD",
            rubricAtoms: ["monotonic deque", "front index eviction", "o(n) amortized"],
          },
          {
            slug: "minimum-window-substring",
            title: "Minimum Window Substring",
            description: "Character frequency counter, matched conditions, contract left.",
            difficulty: "HARD",
            rubricAtoms: ["target map", "window map", "valid count matched"],
          },
          {
            slug: "course-schedule-cycle",
            title: "Course Schedule III (Greedy + Heap)",
            description: "Deadline scheduling, greedy duration replacement.",
            difficulty: "HARD",
            rubricAtoms: ["sort by deadline", "max-heap durations", "time accumulation"],
          },
          {
            slug: "clone-graph-dfs",
            title: "Clone Graph & Deep Copy Data Structures",
            description: "Node mapping table, cycle avoidance during recursive cloning.",
            difficulty: "MEDIUM",
            rubricAtoms: ["visited map", "recursive clone", "neighbor array"],
          },
          {
            slug: "pacific-atlantic-water",
            title: "Pacific Atlantic Water Flow",
            description: "Reverse BFS/DFS from ocean borders, intersection set.",
            difficulty: "MEDIUM",
            rubricAtoms: ["multi-source dfs", "matrix borders", "intersection set"],
          },
          {
            slug: "rotting-oranges-bfs",
            title: "Rotting Oranges (Multi-Source BFS)",
            description: "Simultaneous queue ignition, minute level progression.",
            difficulty: "MEDIUM",
            rubricAtoms: ["multi-source queue", "fresh count", "grid boundaries"],
          },
          {
            slug: "word-ladder-bfs",
            title: "Word Ladder I & II (Shortest Transformation)",
            description: "Bidirectional BFS, intermediate pattern dictionaries.",
            difficulty: "HARD",
            rubricAtoms: ["bidirectional bfs", "wildcard pattern", "path backtrack"],
          },
          {
            slug: "alien-dictionary-topo",
            title: "Alien Dictionary (Graph Ordering)",
            description: "Character pairwise comparison, DAG topological ordering.",
            difficulty: "HARD",
            rubricAtoms: ["first diff char", "in-degree count", "topological queue"],
          },
          {
            slug: "cheapest-flights-k-stops",
            title: "Cheapest Flights Within K Stops (Bellman-Ford)",
            description: "Relaxation iterations, backup distance array.",
            difficulty: "HARD",
            rubricAtoms: ["bellman-ford", "k-steps relax", "bfs with price"],
          },
          {
            slug: "network-delay-time",
            title: "Network Delay Time (Dijkstra)",
            description: "Directed weighted graph, max distance computation.",
            difficulty: "MEDIUM",
            rubricAtoms: ["dijkstra heap", "visited distance", "max time"],
          },
          {
            slug: "target-sum-dp",
            title: "Target Sum (0/1 Subset Sum Transformation)",
            description: "Offset mapping or algebraic subset partition equation.",
            difficulty: "MEDIUM",
            rubricAtoms: ["subset sum equation", "offset dp", "space optimization"],
          },
          {
            slug: "coin-change-fewest",
            title: "Coin Change (Unbounded Knapsack)",
            description: "Fewest coins DP, bottom-up table building.",
            difficulty: "MEDIUM",
            rubricAtoms: ["unbounded knapsack", "subproblem min", "infinity guard"],
          },
          {
            slug: "longest-increasing-subsequence",
            title: "Longest Increasing Subsequence (Patience Sort)",
            description: "Binary search with tails array, O(n log n) efficiency.",
            difficulty: "MEDIUM",
            rubricAtoms: ["patience sort", "tails array", "binary search insert"],
          },
          {
            slug: "maximal-rectangle-matrix",
            title: "Maximal Rectangle in Binary Matrix",
            description: "Row-by-row histogram conversion, stack area evaluation.",
            difficulty: "HARD",
            rubricAtoms: ["histogram conversion", "monotonic stack", "o(r*c) time"],
          },
          {
            slug: "longest-consecutive-sequence",
            title: "Longest Consecutive Sequence (Hash Set)",
            description: "O(n) time sequence discovery, start-of-sequence detection.",
            difficulty: "MEDIUM",
            rubricAtoms: ["hash set", "start of streak", "while count"],
          },
          {
            slug: "subarray-sum-equals-k",
            title: "Subarray Sum Equals K (Prefix Sum + Hash Map)",
            description: "Prefix sum delta lookup, cumulative frequency map.",
            difficulty: "MEDIUM",
            rubricAtoms: ["prefix sum", "cumulative map", "delta match"],
          },
          {
            slug: "product-array-except-self",
            title: "Product of Array Except Self",
            description: "Left prefix products, right suffix products without division.",
            difficulty: "MEDIUM",
            rubricAtoms: ["prefix product", "suffix accumulator", "constant extra space"],
          },
          {
            slug: "gas-station-greedy",
            title: "Gas Station Circuit (Greedy Single Pass)",
            description: "Deficit tracking, start pointer adjustment, total balance.",
            difficulty: "MEDIUM",
            rubricAtoms: ["greedy choice", "surplus balance", "start index"],
          },
          {
            slug: "jump-game-greedy",
            title: "Jump Game I & II (Greedy Range Expansion)",
            description: "Farthest reach calculation, jump count interval progression.",
            difficulty: "MEDIUM",
            rubricAtoms: ["farthest reach", "jump boundary", "greedy range"],
          },
          {
            slug: "merge-k-sorted-lists",
            title: "Merge K Sorted Lists (Divide & Conquer)",
            description: "Pairwise list merge, min-heap head extraction.",
            difficulty: "HARD",
            rubricAtoms: ["divide and conquer", "min-heap", "dummy head join"],
          },
        ],
      },
    ],
  },
  {
    slug: "behavioral",
    name: "Behavioral & Leadership",
    description: "STAR methodology, conflict resolution, engineering leadership, and ownership.",
    categories: [
      {
        slug: "leadership-communication",
        name: "Leadership, Teamwork & Execution",
        description: "Behavioral competencies evaluated for Senior and Staff level engineers.",
        topics: [
          {
            slug: "conflict-resolution-peers",
            title: "Resolving Technical Disagreements with Peers",
            description: "Navigating competing technical designs, data-driven compromise, and consensus.",
            difficulty: "MEDIUM",
            rubricAtoms: ["data-driven decision", "empathy", "consensus building"],
          },
          {
            slug: "delivering-under-ambiguity",
            title: "Delivering Under High Ambiguity & Shifting Deadlines",
            description: "Iterative MVP scoping, stakeholder alignment, risk reduction under pressure.",
            difficulty: "HARD",
            rubricAtoms: ["mvp scoping", "risk reduction", "stakeholder communication"],
          },
          {
            slug: "handling-production-outages",
            title: "Leading Incident Response & Blameless Post-Mortems",
            description: "High-severity incident command, customer communication, root-cause remediation.",
            difficulty: "HARD",
            rubricAtoms: ["incident command", "blameless postmortem", "preventive action items"],
          },
          {
            slug: "managing-technical-debt",
            title: "Balancing Technical Debt vs Product Velocity",
            description: "Quantifying debt impact, negotiating refactoring sprints with product managers.",
            difficulty: "MEDIUM",
            rubricAtoms: ["roi justification", "incremental refactor", "metrics tracking"],
          },
          {
            slug: "mentoring-junior-engineers",
            title: "Mentorship, Delegation & Engineering Culture",
            description: "Growing junior/mid-level teammates, code review culture, multiplying team output.",
            difficulty: "EASY",
            rubricAtoms: ["delegation", "active listening", "constructive feedback"],
          },
          {
            slug: "disagree-and-commit",
            title: "Navigating Top-Down Decisions (Disagree & Commit)",
            description: "Constructively voicing dissent, rallying behind final executive decisions.",
            difficulty: "MEDIUM",
            rubricAtoms: ["constructive dissent", "alignment", "commitment"],
          },
          {
            slug: "managing-difficult-stakeholders",
            title: "Managing Difficult Cross-Functional Stakeholders",
            description: "Bridging engineering constraints with sales, product, and legal demands.",
            difficulty: "MEDIUM",
            rubricAtoms: ["empathy", "clear SLAs", "boundary setting"],
          },
          {
            slug: "failing-project-recovery",
            title: "Turning Around a Stalled or At-Risk Project",
            description: "Re-scoping deliverables, re-energizing demoralized teams, unblocking bottlenecks.",
            difficulty: "HARD",
            rubricAtoms: ["bottleneck diagnosis", "re-prioritization", "morale boost"],
          },
          {
            slug: "giving-critical-feedback",
            title: "Delivering Difficult Feedback to Team Members",
            description: "Timely, actionable, private feedback that drives tangible behavior improvement.",
            difficulty: "MEDIUM",
            rubricAtoms: ["radical candor", "actionable steps", "growth focus"],
          },
          {
            slug: "saying-no-to-scope-creep",
            title: "Protecting Team Bandwidth Against Scope Creep",
            description: "Firm boundary management, data-backed capacity models, polite refusal.",
            difficulty: "MEDIUM",
            rubricAtoms: ["capacity modeling", "trade-off framing", "firm boundaries"],
          },
          {
            slug: "navigating-organizational-change",
            title: "Leading Through Reorgs & Strategic Pivots",
            description: "Maintaining morale, retaining focus, adapting team roadmaps rapidly.",
            difficulty: "HARD",
            rubricAtoms: ["resilience", "roadmap pivot", "transparent leadership"],
          },
          {
            slug: "cross-team-dependency-delays",
            title: "Unblocking Cross-Team Blockers & Missing SLAs",
            description: "Escalating constructively, establishing shared interface contracts, joint ownership.",
            difficulty: "MEDIUM",
            rubricAtoms: ["contract first", "constructive escalation", "joint review"],
          },
          {
            slug: "promoting-diversity-inclusion",
            title: "Fostering Psychological Safety & Inclusive Culture",
            description: "Encouraging quiet voices, mitigating bias in hiring, equitable promotion discussions.",
            difficulty: "EASY",
            rubricAtoms: ["psychological safety", "bias awareness", "inclusive review"],
          },
          {
            slug: "advocating-for-innovation",
            title: "Securing Buy-In for Architecture Overhauls",
            description: "Drafting persuasive RFCs/ADRs, creating low-risk prototypes to prove value.",
            difficulty: "HARD",
            rubricAtoms: ["rfc process", "prototype validation", "business value alignment"],
          },
          {
            slug: "recovering-from-personal-mistake",
            title: "Taking Accountability for a Costly Error",
            description: "Immediate disclosure, owning remediation, implementing systemic guardrails.",
            difficulty: "MEDIUM",
            rubricAtoms: ["ownership", "transparent disclosure", "systemic guardrail"],
          },
          {
            slug: "handling-underperforming-teammate",
            title: "Supporting and Managing Underperformance",
            description: "Diagnosing root causes (skill vs will), PIP guidance, compassionate accountability.",
            difficulty: "HARD",
            rubricAtoms: ["root cause analysis", "clear expectations", "regular checkpoints"],
          },
          {
            slug: "influencing-without-authority",
            title: "Influencing Technical Roadmaps Without Formal Authority",
            description: "Building grassroots alliances, demonstrating empirical results, writing crisp ADRs.",
            difficulty: "HARD",
            rubricAtoms: ["peer influence", "grassroots proof", "crisp documentation"],
          },
          {
            slug: "driving-operational-excellence",
            title: "Instilling High Testing and Reliability Standards",
            description: "Elevating test coverage, SLO/SLA hygiene, reducing on-call fatigue.",
            difficulty: "MEDIUM",
            rubricAtoms: ["on-call reduction", "slo adoption", "testing culture"],
          },
          {
            slug: "communicating-with-executives",
            title: "Presenting Complex Technical Concepts to Executives",
            description: "Bottom-line first (Minto Pyramid), framing engineering investment in business terms.",
            difficulty: "HARD",
            rubricAtoms: ["minto pyramid", "business value translation", "executive summary"],
          },
          {
            slug: "managing-burnout-sustainability",
            title: "Sustaining Sustainable Engineering Pace & Wellbeing",
            description: "Identifying burnout signals, pacing on-call schedules, long-term team health.",
            difficulty: "EASY",
            rubricAtoms: ["workload balancing", "on-call rotations", "sustainable velocity"],
          },
        ],
      },
    ],
  },
  {
    slug: "cloud",
    name: "Cloud & Infrastructure",
    description: "AWS/GCP architectures, Kubernetes, resilience, cost optimization, and networking.",
    categories: [
      {
        slug: "cloud-reliability-devops",
        name: "Cloud Architecture & Site Reliability",
        description: "Infrastructure engineering, container orchestration, and reliability.",
        topics: [
          {
            slug: "multi-region-vpc-architecture",
            title: "Multi-Region VPC & High Availability Peering",
            description: "VPC peering, AWS Transit Gateway, cross-region latency, split-horizon DNS.",
            difficulty: "HARD",
            rubricAtoms: ["transit gateway", "vpc peering", "route53 latency routing"],
          },
          {
            slug: "kubernetes-eks-autoscaling",
            title: "Kubernetes (EKS/GKE) Cluster Autoscaling",
            description: "HPA, VPA, Karpenter vs Cluster Autoscaler, pod disruption budgets.",
            difficulty: "HARD",
            rubricAtoms: ["karpenter", "hpa metric", "pod disruption budget"],
          },
          {
            slug: "serverless-event-driven",
            title: "Serverless Event-Driven Architectures (Lambda/EventBridge)",
            description: "Cold starts, concurrency limits, EventBridge buses, dead-letter queues.",
            difficulty: "MEDIUM",
            rubricAtoms: ["eventbridge", "lambda cold start", "dlq error handling"],
          },
          {
            slug: "cloud-cost-finops",
            title: "FinOps & Cloud Cost Optimization Strategies",
            description: "Reserved instances, Savings Plans, S3 lifecycle tiers, spot instance fleets.",
            difficulty: "MEDIUM",
            rubricAtoms: ["spot fleet", "s3 intelligent tiering", "finops anomaly detection"],
          },
          {
            slug: "zero-trust-identity-iam",
            title: "Zero-Trust Architecture & Cloud IAM Least Privilege",
            description: "IAM roles, STS assume-role, service accounts (IRSA), OAuth2 OIDC federations.",
            difficulty: "HARD",
            rubricAtoms: ["irsa", "sts token", "least privilege iam"],
          },
          {
            slug: "ddos-waf-mitigation",
            title: "Cloudflare / AWS WAF & DDoS Mitigation Patterns",
            description: "Rate-based rules, CAPTCHA challenges, origin shielding, Shield Advanced.",
            difficulty: "MEDIUM",
            rubricAtoms: ["waf rate rules", "origin shield", "syn flood mitigation"],
          },
          {
            slug: "container-security-supply-chain",
            title: "Container Security & Supply Chain Defense",
            description: "Trivy image scanning, cosign signature verification, distroless runtime images.",
            difficulty: "MEDIUM",
            rubricAtoms: ["image scanning", "distroless base", "cosign signature"],
          },
          {
            slug: "terraform-iac-at-scale",
            title: "Infrastructure as Code (Terraform & OpenTofu)",
            description: "Remote state locking, module composition, drift detection, GitOps pipelines.",
            difficulty: "MEDIUM",
            rubricAtoms: ["s3 backend lock", "module abstraction", "terraform plan checks"],
          },
          {
            slug: "kubernetes-ingress-mesh",
            title: "Ingress Controllers & Envoy Service Mesh",
            description: "NGINX Ingress vs Traefik vs Istio, mTLS between microservices, traffic splitting.",
            difficulty: "HARD",
            rubricAtoms: ["istio mtls", "canary traffic split", "ingress controller"],
          },
          {
            slug: "database-aurora-global",
            title: "Amazon Aurora Global Database Replication",
            description: "Physical storage replication, cross-region write forwarding, sub-second lag.",
            difficulty: "HARD",
            rubricAtoms: ["storage replication", "write forwarding", "global database failover"],
          },
          {
            slug: "cloud-monitoring-otel",
            title: "Cloud Observability & OpenTelemetry Collectors",
            description: "Prometheus agent mode, Grafana Tempo, Loki distributed log aggregation.",
            difficulty: "MEDIUM",
            rubricAtoms: ["otel collector", "tempo traces", "loki log labels"],
          },
          {
            slug: "disaster-recovery-active-active",
            title: "Multi-Cloud & Active-Active Disaster Recovery",
            description: "Global traffic manager, bidirectional database replication, conflict resolution.",
            difficulty: "HARD",
            rubricAtoms: ["active-active replication", "dns health failover", "conflict-free replication"],
          },
          {
            slug: "kubernetes-secrets-vault",
            title: "Kubernetes Secrets Management (HashiCorp Vault)",
            description: "External Secrets Operator, dynamic database credentials, secret rotation.",
            difficulty: "HARD",
            rubricAtoms: ["external secrets operator", "vault sidecar", "dynamic credential rotation"],
          },
          {
            slug: "s3-lakehouse-architecture",
            title: "S3 Data Lakehouse Architecture (Iceberg / Delta)",
            description: "Parquet partitioning, Apache Iceberg metadata catalogs, Athena queries.",
            difficulty: "HARD",
            rubricAtoms: ["apache iceberg", "s3 partition projection", "athena cost optimization"],
          },
          {
            slug: "api-gateway-rate-limiting",
            title: "Cloud API Gateway & Usage Plans (Kong / Apigee)",
            description: "API key quotas, JWT validation, Redis distributed token buckets.",
            difficulty: "MEDIUM",
            rubricAtoms: ["api usage plans", "jwt edge validation", "kong ingress"],
          },
          {
            slug: "grpc-envoy-loadbalancing",
            title: "gRPC Load Balancing & HTTP/2 Multiplexing",
            description: "L4 connection reuse problem, Envoy client-side vs lookaside load balancing.",
            difficulty: "HARD",
            rubricAtoms: ["http/2 streams", "envoy l7 balancer", "lookaside balancing"],
          },
          {
            slug: "cicd-gitops-argocd",
            title: "GitOps Continuous Delivery with ArgoCD",
            description: "Declarative cluster states, automated sync, rollbacks, blue-green deployments.",
            difficulty: "MEDIUM",
            rubricAtoms: ["argocd application", "blue-green rollouts", "gitops sync window"],
          },
          {
            slug: "cloud-network-security-groups",
            title: "Network Access Control Lists & Security Groups",
            description: "Stateful security groups vs stateless NACLs, egress filtering, private subnets.",
            difficulty: "EASY",
            rubricAtoms: ["stateful rules", "stateless nacl", "nat gateway routing"],
          },
          {
            slug: "hybrid-cloud-direct-connect",
            title: "Hybrid Cloud Connectivity (AWS Direct Connect / VPN)",
            description: "BGP routing, IPsec tunnels, Direct Connect gateways, redundant connections.",
            difficulty: "HARD",
            rubricAtoms: ["bgp routing", "ipsec redundancy", "direct connect gateway"],
          },
          {
            slug: "kafka-mskf-clustering",
            title: "Managed Streaming for Apache Kafka (Amazon MSK)",
            description: "Broker sizing, storage auto-expansion, mirror maker cross-cluster replication.",
            difficulty: "HARD",
            rubricAtoms: ["msk cluster", "mirrormaker", "tier storage"],
          },
          {
            slug: "redis-elasticache-clustering",
            title: "Redis ElastiCache Cluster Mode & Sharding",
            description: "Multi-AZ with auto-failover, cluster mode enabled, hash slots distribution.",
            difficulty: "MEDIUM",
            rubricAtoms: ["hash slot 16384", "multi-az failover", "read replica endpoints"],
          },
          {
            slug: "chaos-engineering-cloud",
            title: "Chaos Engineering & Fault Injection (Gremlin / Chaos Mesh)",
            description: "Simulating pod kills, network latency, region blackhole testing.",
            difficulty: "HARD",
            rubricAtoms: ["fault injection", "chaos experiment", "blast radius control"],
          },
          {
            slug: "cloud-data-sovereignty-gdpr",
            title: "Data Residency & Cloud Compliance (GDPR/HIPAA)",
            description: "Encryption at rest (KMS envelope encryption), audit logging via CloudTrail.",
            difficulty: "MEDIUM",
            rubricAtoms: ["kms envelope", "cloudtrail data events", "data residency lock"],
          },
          {
            slug: "dynamodb-single-table-design",
            title: "Amazon DynamoDB Single-Table Design",
            description: "Partition keys, sort keys, sparse global secondary indexes, overloaded keys.",
            difficulty: "HARD",
            rubricAtoms: ["pk/sk patterns", "gsi index overloading", "atomic counters"],
          },
          {
            slug: "edge-computing-cloudflare-workers",
            title: "Edge Compute & Serverless KV (Cloudflare Workers)",
            description: "V8 isolates vs containers, global KV caching, edge personalization.",
            difficulty: "MEDIUM",
            rubricAtoms: ["v8 isolate", "edge kv", "sub-10ms response"],
          },
        ],
      },
    ],
  },
];

async function main() {
  console.log("🌱 Starting PrepInMinutes Curriculum Seed...");
  let totalTopics = 0;

  for (const domainData of DOMAINS_DATA) {
    const domain = await prisma.curriculumDomain.upsert({
      where: { slug: domainData.slug },
      update: { name: domainData.name, description: domainData.description },
      create: { slug: domainData.slug, name: domainData.name, description: domainData.description },
    });
    console.log(`✓ Domain: ${domain.name} (${domain.slug})`);

    for (const catData of domainData.categories) {
      const category = await prisma.curriculumCategory.upsert({
        where: { domainId_slug: { domainId: domain.id, slug: catData.slug } },
        update: { name: catData.name, description: catData.description },
        create: {
          domainId: domain.id,
          slug: catData.slug,
          name: catData.name,
          description: catData.description,
        },
      });

      for (const topicData of catData.topics) {
        await prisma.curriculumTopic.upsert({
          where: { slug: topicData.slug },
          update: {
            title: topicData.title,
            description: topicData.description,
            difficulty: topicData.difficulty,
            rubricAtoms: topicData.rubricAtoms,
            domainId: domain.id,
            categoryId: category.id,
          },
          create: {
            slug: topicData.slug,
            title: topicData.title,
            description: topicData.description,
            difficulty: topicData.difficulty,
            rubricAtoms: topicData.rubricAtoms,
            domainId: domain.id,
            categoryId: category.id,
            durationMin: 15,
            practiceHref: `/practice/session/${domain.slug}`,
          },
        });
        totalTopics++;
      }
    }
  }

  console.log(`\n🎉 Successfully seeded ${totalTopics} curriculum topics across 4 domains!`);
  await prisma.$disconnect();
}

main().catch((err) => {
  console.error("❌ Seeding failed:", err);
  process.exit(1);
});
